apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-chat
spec:
  project: default
  source:
    repoURL: https://github.com/resonating-sirsh/one-chat.git
    path: app/manifest
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
