apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: 286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test
  newTag: one-chat-53d5b74e978ed0613594d97bd22aee43db1b1329
